### ISSUE TITLE
connect to server over https

### ISSUE THREAD

**Issue by gartensofa** [stanford-oval/genie-client#61]
I try to run a genie-client on my raspberry pi zero w.
When i try to connect to a genie server on home assistant 
(installed like this: https://wiki.genie.stanford.edu/getting-started/installation-guide/3rd-party-home-assistant-addon) 
i get the following errors:

`(genie-client:1382): genie::conversation::Client-WARNING **: 23:15:53.503: Failed to get access token from Home Assistant: (null)
genie::conversation::Client-Message: 23:15:56.511: Requesting Home Assistant session token from http://192.168.20.4:443/api/hassio/ingress/session
genie::conversation::Client-Message: 23:15:56.534: Sent access token request to Home Assistant, got HTTP 8
`
my config is as follows:
`[general]
url=https://192.168.20.4:443/api/hassio_ingress/IdKw5rkogeJyopPlD8cc4CDZaZoUmXuUY5apDSLNCqs/api/conversation
auth_mode=home-assistant
accessToken=*redacted*
conversationId=genie-wz`

i also added these lines, with no difference:
`
[system]
ssl_strict=false
ssl_ca_file=/home/pi/ca.*redacted*.crt
`
is it supported to connect via https or am i doing it wrong?

**Comment by gcampax** [comment]
The configuration looks correct, except `https` should be `wss` in the url
Do you have a good TLS certificate (issued by a CA like letsencrypt) or is it self signed? If self-signed, I'm not sure we currently support that. We might need to pass additional options to libsoup to handle a self-signed certificate.

**Comment by gcampax** [comment]
Also, could you try setting `ssl_strict=false` without also setting `ssl_ca_file` ?

**Comment by maybeinit** [comment]
Thanks, had a similar issue and using `wss://` solved it.

The home assistant add-on suggested to use `http://` under the "External Clients" configuration section and I thought it was as simple as changing it to `https://`, not the case, hah!

**Comment by gcampax** [comment]
Oh thanks for the report, I just fixed the configuration page, it should show ws now

**Comment by gartensofa** [comment]
Wow, you guys move fast.
setting the url to `wss://` and setting `ssl_strict=false` fixed it for me too.
I was trying to get things working with `ssl_strict=true` and a `ssl_ca_file`, but i got some issues in my ssl load balancer, 
so sadly i cannot comment to this at the moment.

But it works for testing now, so thanks a bunch!

**Comment by gcampax** [comment]
Great to hear it works, closing!
